### ISSUE TITLE
Support for vendored OpenSSL

### ISSUE THREAD

**Issue by mkpankov** [sfackler/tokio-openssl#39]
I want to use vendored OpenSSL. There's a feature `vendored` in `rust-openssl`, but it's not supported upwards

**Comment by sfackler** [comment]
```toml
[dependencies]
tokio-openssl = "0.6"
openssl = { version = "0.10", features = ["vendored"] }
```
